owner: 3Deling-IT
repo: status

#SITES
sites:
  - name: 3Deling
    url: $MAIN_SITE
    icon: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/3d-favicon.ico
  - name: Owncloud
    url: $OWNCLOUD_SITE
    method: GET
    icon: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/oc-favicon.ico
  - name: Support
    url: $SUPPORT_SITE
    method: GET
    icon: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/sp-favicon.svg
  - name: Web Pano
    url: $PANO_SITE
    icon: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/wp-favicon.ico
    method: GET
  - name: TVE
    url: $TVE_SITE
    method: GET
    icon: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/tve-favicon.ico
  - name: Sentry
    url: $SENTRY_SITE
    method: GET
    icon: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/sentry-favicon.ico
  - name: ERP
    url: $ERP_SITE
    method: GET
    icon: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/erp-favicon.ico
  - name: Clients Portal
    url: $CLIENTS_SITE
    method: GET
    icon: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/cp-favicon.ico

#SETTINGS
status-website:
  cname: status.3deling.com
  logoUrl: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/3d-logo.svg
  name: 3Deling Status Page
  introTitle: "**3Deling Status Page**"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
  favicon: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/3d-favicon.ico
  metaTags:
    - name: "robots"
      content: "noindex,nofollow"
