# Change these first
owner: 3Deling-IT # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: 3Deling
    url: $MAIN_SITE
  - name: Owncloud
    url: $OWNCLOUD_SITE
    method: GET
  - name: Support
    url: $SUPPORT_SITE
    method: GET
  - name: Web Pano
    url: $PANO_SITE
    icon: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/wp-favicon.ico
    method: GET
  - name: TVE
    url: $TVE_SITE
    method: GET
  - name: Sentry
    url: $SENTRY_SITE
    method: GET
  - name: ERP
    url: $ERP_SITE
    method: GET
  - name: Clients Portal
    url: $CLIENTS_SITE
    method: GET

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.3deling.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/3d-logo.svg
  name: 3Deling Status Page
  introTitle: "**3Deling Status Page**"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
  favicon: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/favicon.ico
  metaTags:
    - name: "robots"
      content: "noindex,nofollow"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
