# Change these first
owner: 3Deling-IT # Your GitHub username
repo: status # Your GitHub repository name

# Add your sites here
sites:
  - name: 3Deling
    url: 185.70.180.209
  - name: Fileshare
    url: https://fileshare.3deling.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.3deling.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/3d-logo.svg
  name: 3Deling Status Page
  introTitle: "**3Deling Status Page**"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: light
  favicon: https://raw.githubusercontent.com/3Deling-IT/status/master/assets/favicon.ico
  metaTags:
      - name: "robots"
      content: "noindex,nofollow"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
